nombre="Luis Arias"
print("")
print("Empezando a trabajar con Python")
strcom="Realizado por : \t{0}".format("Luis Arias")
print(strcom)
print("")
print("Consultando los tipos de valores")
print("")
print("El tipo de dato de 875 es: ")
print(type(875))
print("")
print("El tipo de dato de 4.89 es: ")
print(type(4.89))
print("")
print("El tipo de dato del texto: Now is better than never. es: ")
print(type("Now is better than never es"))
print("")
print("El tipo de dato de 1.32 es: ")
print(type(1.32))
print("")
print("¿El valor 5+8i corresponde a un valor entero?")
print(isinstance(5+8j, int))
print("")
print("¿El valor 8.2 corresonde a un valor entero?")
print(isinstance(8.2, int))
print("")
print("¿El texto: Readability count. corresponde a un string?")
print(isinstance("Readability count", str))