print("")
print("Programa que identifica el tipo de dato de un valor ingresado por el usuario, se realizaràn cinco interacciones:")
print("")
var1=int(input("Primera Interaccion, ingrese un valor cualquiera: "))
print("Este tipo de dato en Python es: ")
print(type(var1))
print("")
var2=float(input("Segunda Interaccion, ingrese un valor cualquiera: "))
print("Este tipo de dato en Python es: ")
print(type(var2))
print("")
var3=complex(input("tercera Interaccion, ingrese un valor cualquiera: "))
print("Este tipo de dato en Python es: ")
print(type(var3))
print("")
var4=input("Cuarta Interaccion, ingrese un valor cualquiera: ")
print("Este tipo de dato en Python es: ")
print(type(var4))
print("")
var5=bool(input("Quinta Interaccion, ingrese un valor cualquiera: "))
print("Este tipo de dato en Python es: ")
print(type(var5))
print("")